name: Vulnerable Workflow
on:
  pull_request_target:
    types: [opened]
jobs:
  vulnerable_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Vulnerable Step
        run: |
          # This script is from the PR, so it can be malicious
          ./run.sh
