name: Vulnerable Workflow
on:
  push:
    branches: [ main ]
jobs:
  vulnerable_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          # This workflow is vulnerable to dependency confusion if a package
          # with the same name as an internal package is published to a public registry.
          npm install
