name: Vulnerable Workflow
on:
  pull_request:
    types: [opened]
jobs:
  vulnerable_job:
    runs-on: ubuntu-latest
    steps:
      - name: Vulnerable Step
        run: |
          echo "PR title: ${{ github.event.pull_request.title }}"
          # The following line is vulnerable to command injection
          echo "Running command with PR title: ${{ github.event.pull_request.title }}"
