name: Fixed Workflow
on:
  pull_request:
    types: [opened]
jobs:
  fixed_job:
    runs-on: ubuntu-latest
    steps:
      - name: Fixed Step
        env:
          PR_BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          echo "PR branch: $PR_BRANCH"
          # The following line is now safe from command injection
          echo "Running command with PR branch: $PR_BRANCH"
