name: Vulnerable Workflow
on:
  pull_request:
    types: [opened]
jobs:
  vulnerable_job:
    runs-on: ubuntu-latest
    steps:
      - name: Vulnerable Step
        run: |
          echo "PR branch: ${{ github.event.pull_request.head.ref }}"
          # The following line is vulnerable to command injection
          echo "Running command with PR branch: ${{ github.event.pull_request.head.ref }}"
