name: Vulnerable Workflow
on:
  pull_request_target:
    types: [opened]
jobs:
  vulnerable_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Vulnerable Step
        run: |
          # This workflow is triggered on pull_request_target,
          # which has access to secrets, but checks out untrusted code.
          echo "Running with secrets!"
          echo ${{ secrets.MY_SECRET }}
