name: Vulnerable Workflow
on:
  push:
    branches: [ main ]
jobs:
  vulnerable_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Vulnerable Action
        uses: some-user/some-action@main
