name: Vulnerable Workflow
on:
  issue_comment:
    types: [created]
jobs:
  vulnerable_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const comment = context.payload.comment.body;
            // This script is vulnerable because it's running with access to secrets
            // and can be influenced by the comment body.
            console.log(`Comment: ${comment}`);
