name: Vulnerable Workflow
on:
  pull_request_target:
    types: [opened]
jobs:
  vulnerable_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            // This script is vulnerable because it's running in the context of pull_request_target
            // and can be influenced by the PR's title.
            console.log(`PR title: ${pr.title}`);
